version: 2
updates:
  - package-ecosystem: "make" # Specifies Makefile dependencies
    directory: "/" # Location of Makefile
    schedule:
      interval: "weekly" # Frequency of updates: daily, weekly, monthly
  - package-ecosystem: "cmake" # Specifies CMake dependencies
    directory: "/" # Location of CMakeLists.txt
    schedule:
      interval: "weekly" # Frequency of updates: daily, weekly, monthly
