version: 2
updates:
  - package-ecosystem: "conan" # Specifies Conan dependencies
    directory: "/" # Location of conanfile.txt or conanfile.py
    schedule:
      interval: "weekly" # Frequency of updates: daily, weekly, monthly
